/* KDL — catálogo compartido (Home + Productos + Producto) */
(function(){
  function slug(s){
    return (s||'').toString().toLowerCase()
      .normalize('NFD').replace(/[\u0300-\u036f]/g,'')
      .replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
  }
  var imgMap={
    neumatica:'assets/catalog/cat-neumatica.png',
    hidraulica:'assets/catalog/cat-hidraulica.png',
    sensores:'assets/catalog/cat-sensores.png',
    automatizacion:'assets/catalog/cat-automatizacion.png',
    movimiento:'assets/catalog/cat-movimiento.png',
    corte:'assets/catalog/cat-corte.png',
    iqf:'assets/catalog/cat-iqf.png',
    electrico:'assets/catalog/cat-electrico.png',
    suministros:'assets/catalog/cat-suministros.png'
  };
  var productImgMap={
    'cilindros-iso-15552':'assets/catalog/pneumatic-cylinder-iso.png',
    'minicilindros-iso-6432':'assets/catalog/pneumatic-mini-cylinder.png',
    'minicilindros-aluminio-ma':'assets/catalog/pneumatic-mini-cylinder.png',
    'cilindros-compactos-cq2':'assets/catalog/pneumatic-compact-cylinder.png',
    'cilindro-compacto-sda':'assets/catalog/pneumatic-compact-cylinder.png',
    'cilindros-clean-cm2-cj2':'assets/catalog/pneumatic-clean-cylinder.png',
    'cilindros-guiados-mgp':'assets/catalog/pneumatic-guided-cylinder.png',
    'cilindros-rotacionales-msq':'assets/catalog/pneumatic-rotary-cylinder.png',
    'twin-rod-tn-tr':'assets/catalog/pneumatic-twin-rod.png',
    'twist-clamp-cylinder':'assets/catalog/pneumatic-clamp-cylinder.png',
    'grippers-neumaticos':'assets/catalog/pneumatic-gripper.png',
    'amortiguadores-hidraulicos':'assets/catalog/pneumatic-shock.png',
    'chumacera-lineal-sbr-35uu':'assets/catalog/motion-guide.png',
    'filtros-reguladores-ack-frl':'assets/catalog/pneumatic-frl.png',
    'bombas-hidraulicas':'assets/catalog/hydraulic-pump-motor.png',
    'motores-hidraulicos':'assets/catalog/hydraulic-pump-motor.png',
    'valvulas-direccionales':'assets/catalog/hydraulic-valves.png',
    'valvulas-proporcionales':'assets/catalog/hydraulic-valves.png',
    'servo-valvulas':'assets/catalog/hydraulic-valves.png',
    'cilindros-hidraulicos':'assets/catalog/hydraulic-cylinder.png',
    'unidades-de-potencia-hpu':'assets/catalog/hydraulic-hpu.png',
    'sistemas-integrados':'assets/catalog/hydraulic-hpu.png',
    'fotoelectricos-omron':'assets/catalog/sensor-photoelectric.png',
    'inductivos-y-capacitivos':'assets/catalog/sensor-ifm.png',
    'sensores-laser':'assets/catalog/sensor-photoelectric.png',
    'medicion-color-y-contraste':'assets/catalog/sensor-vision.png',
    'sensores-de-presion-ifm':'assets/catalog/sensor-pressure.png',
    'io-link-masters-ifm':'assets/catalog/sensor-io-link.png',
    'modulos-e-s-y-gateways':'assets/catalog/sensor-io-link.png',
    'rfid-omron':'assets/catalog/sensor-rfid.png',
    'vision-artificial-omron':'assets/catalog/sensor-vision.png',
    'plc-automation-controller':'assets/catalog/automation-plc.png',
    'hmi-delta':'assets/catalog/automation-hmi.png',
    'variadores-de-frecuencia-delta':'assets/catalog/automation-drive.png',
    'servomotores-y-drives-delta':'assets/catalog/automation-servo.png',
    'motores-industriales-delta':'assets/catalog/automation-motor.png',
    'comunicacion-industrial':'assets/catalog/automation-control.png',
    'guias-lineales-hg-qh':'assets/catalog/motion-guide.png',
    'guias-compactas-mg':'assets/catalog/motion-guide.png',
    'husillos-de-bolas':'assets/catalog/motion-ballscrew.png',
    'actuadores-lineales':'assets/catalog/motion-actuator.png',
    'motores-lineales-y-servos':'assets/catalog/motion-servo.png',
    'sistemas-y-etapas-lineales':'assets/catalog/motion-system.png',
    'robots-y-multieje':'assets/catalog/motion-system.png',
    'modulos-ejes-cartesianos':'assets/catalog/motion-system.png',
    'insertos-acero-acabado':'assets/catalog/cutting-turning.png',
    'insertos-acero-semiacabado':'assets/catalog/cutting-square.png',
    'insertos-acero-desbaste':'assets/catalog/cutting-triangle.png',
    'acero-inoxidable':'assets/catalog/cutting-vnmg.png',
    'torneado-hierro-fundido':'assets/catalog/cutting-square.png',
    'insertos-para-aluminio':'assets/catalog/cutting-turning.png',
    'corte-y-ranurado':'assets/catalog/cutting-grooving.png',
    'insertos-de-cermet':'assets/catalog/cutting-cermet.png',
    'insertos-ceramicos':'assets/catalog/cutting-ceramic.png',
    'tronzado-y-ranurado':'assets/catalog/cutting-grooving.png',
    'insertos-de-roscado':'assets/catalog/cutting-threading.png',
    'torno-tipo-suizo':'assets/catalog/cutting-grooving.png',
    'carburo-solido':'assets/catalog/cutting-solid-carbide.png',
    'grados-cvd':'assets/catalog/cutting-grades.png',
    'grados-pvd':'assets/catalog/cutting-grades.png',
    'equipos-de-congelacion-iqf':'assets/catalog/iqf-room.png',
    'tuneles-congeladores-de-banda':'assets/catalog/iqf-tunnel.png',
    'sistemas-mecanicos-y-electricos':'assets/catalog/iqf-room.png',
    'soluciones-para-acuacultura':'assets/catalog/iqf-tunnel.png',
    'equipos-personalizables':'assets/catalog/iqf-room.png',
    'fuentes-de-alimentacion':'assets/catalog/electrical-power.png',
    'relevadores-y-contactores':'assets/catalog/electrical-components.png',
    'proteccion-y-breakers':'assets/catalog/electrical-components.png',
    'borneras-y-riel-din':'assets/catalog/electrical-controls.png',
    'botones-pilotos-y-senalizacion':'assets/catalog/electrical-controls.png',
    'componentes-de-mantenimiento':'assets/catalog/supplies-maintenance.png',
    'transmision-de-potencia':'assets/catalog/supplies-maintenance.png',
    'sujecion-y-fijacion':'assets/catalog/supplies-maintenance.png',
    'consumibles-industriales':'assets/catalog/supplies-maintenance.png'
  };
  var cats=[
    {key:'neumatica', name:'Neumática industrial', brand:'AirTAC', intro:'Cilindros, grippers, conexiones y tratamiento de aire para automatización.',
     filtros:['Cilindros','Válvulas','FRL / aire','Grippers','Conexiones','Vacío'],
     datos:['Diámetro y carrera','Tipo (ISO, compacto, guiado)','Marca / No. de parte','Presión de trabajo','Conexión y montaje'],
     fallas:['Fuga por sellos gastados','Ciclo lento o sin retorno','Válvula pegada o quemada'],
     aplicaciones:['Sujeción y manipulación','Estaciones de ensamble','Automatización de líneas'],
     products:[
      {n:'Cilindros ISO 15552', s:'Ø32–320 mm · carreras hasta 2000 mm'},
      {n:'Minicilindros ISO 6432', s:'Ø8–25 mm · doble efecto'},
      {n:'Minicilindros aluminio MA', s:'1.5 MPa (15 bar) · simple / doble efecto'},
      {n:'Cilindros compactos CQ2', s:'Ø12, 16, 20, 25, 32–100 mm'},
      {n:'Cilindro compacto SDA', s:'compacto, doble efecto'},
      {n:'Cilindros Clean CM2 / CJ2', s:'CM2 Ø20–40 · CJ2 serie 6/10/16'},
      {n:'Cilindros guiados MGP', s:'guiados compactos · posición'},
      {n:'Cilindros rotacionales MSQ', s:'tamaños 10–200'},
      {n:'Twin-rod TN / TR', s:'cilindro de doble vástago'},
      {n:'Twist Clamp Cylinder', s:'sujeción con giro'},
      {n:'Grippers neumáticos', s:'10–500 N · carrera 5–30 mm · ±0.01 mm'},
      {n:'Amortiguadores hidráulicos', s:'absorbedores de impacto'},
      {n:'Chumacera lineal SBR 35UU', s:'soporte de eje lineal'},
      {n:'Filtros reguladores ACK (FRL)', s:'tratamiento de aire comprimido'}
     ]},
    {key:'hidraulica', name:'Hidráulica industrial', brand:'Bosch Rexroth', intro:'Potencia hidráulica para prensas, inyección y maquinaria pesada.',
     filtros:['Cilindros','Bombas','Válvulas','Unidades de potencia','Mangueras','Acumuladores'],
     datos:['Presión y caudal','Diámetro / carrera','Tipo de válvula','Conexiones','Fluido y temperatura'],
     fallas:['Pérdida de presión','Fuga externa o interna','Sobrecalentamiento'],
     aplicaciones:['Prensas','Inyección','Maquinaria pesada'],
     products:[
      {n:'Bombas hidráulicas', s:'de pistones axiales y radiales'},
      {n:'Motores hidráulicos', s:'alta densidad de par'},
      {n:'Válvulas direccionales', s:'control de dirección de flujo'},
      {n:'Válvulas proporcionales', s:'control continuo de caudal'},
      {n:'Servo válvulas', s:'respuesta dinámica de precisión'},
      {n:'Cilindros hidráulicos', s:'industriales, alta presión'},
      {n:'Unidades de potencia (HPU)', s:'centrales hidráulicas'},
      {n:'Sistemas integrados', s:'soluciones personalizadas'}
     ]},
    {key:'sensores', name:'Sensores y control', brand:'IFM · OMRON', intro:'Detección, medición, visión, RFID y comunicación industrial.',
     filtros:['Inductivos','Fotoeléctricos','Capacitivos','Presión','Visión / RFID','IO-Link'],
     datos:['Distancia de detección','Salida (PNP / NPN)','Conexión (M8 / M12)','Voltaje','Material a detectar'],
     fallas:['Lectura intermitente','Sin señal','Daño por golpe o temperatura'],
     aplicaciones:['Conteo y posición','Detección de presencia','Medición de proceso'],
     products:[
      {n:'Fotoeléctricos OMRON', s:'E3Z · E3X (fibra óptica)'},
      {n:'Inductivos y capacitivos', s:'detección de presencia / posición'},
      {n:'Sensores láser', s:'alta precisión de distancia'},
      {n:'Medición, color y contraste', s:'amplificador inteligente · IO-Link'},
      {n:'Sensores de presión IFM', s:'hasta 600 bar (especiales 1000 bar)'},
      {n:'IO-Link Masters IFM', s:'series AL · DL · TB'},
      {n:'Módulos E/S y gateways', s:'E/S descentralizadas · IIoT · Edge'},
      {n:'RFID OMRON', s:'sistemas HF y UHF · trazabilidad'},
      {n:'Visión artificial OMRON', s:'FH Series · FHV7 · AI Vision'}
     ]},
    {key:'automatizacion', name:'Automatización', brand:'OMRON · DELTA', intro:'PLC, HMI, variadores, servos y comunicación de procesos.',
     filtros:['PLC','HMI','Variadores','Servomotores','I/O','Fuentes'],
     datos:['Marca y modelo','Voltaje / potencia','Protocolo de comunicación','No. de parte','Aplicación'],
     fallas:['Código de error','Equipo descontinuado','Comunicación caída'],
     aplicaciones:['Control de línea','Dosificación','Manejo de motores'],
     products:[
      {n:'PLC / Automation Controller', s:'OMRON · lógica, movimiento, visión'},
      {n:'HMI DELTA', s:'alarmas, recetas, tendencias'},
      {n:'Variadores de frecuencia DELTA', s:'velocidad, par y posición'},
      {n:'Servomotores y drives DELTA', s:'alto desempeño'},
      {n:'Motores industriales DELTA', s:'alta confiabilidad'},
      {n:'Comunicación industrial', s:'EtherCAT · EtherNet/IP · IO-Link · OPC UA'}
     ]},
    {key:'movimiento', name:'Movimiento lineal', brand:'HIWIN', intro:'Guías, husillos, actuadores y sistemas multieje de precisión.',
     filtros:['Guías','Husillos','Actuadores','Patines','Multieje','Soportes'],
     datos:['Tamaño / serie','Longitud de carrera','Precarga y precisión','Carga y velocidad','Marca / No. de parte'],
     fallas:['Juego o ruido','Pérdida de precisión','Desgaste de patín'],
     aplicaciones:['CNC','Pick & place','Ejes cartesianos'],
     products:[
      {n:'Guías lineales HG / QH', s:'rail + bloque · alta precisión'},
      {n:'Guías compactas MG', s:'miniatura, espacios reducidos'},
      {n:'Husillos de bolas', s:'ballscrews · giro a lineal'},
      {n:'Actuadores lineales', s:'motor + guía integrados'},
      {n:'Motores lineales y servos', s:'control de velocidad y posición'},
      {n:'Sistemas y etapas lineales', s:'listos para instalar'},
      {n:'Robots y multieje', s:'automatización avanzada'},
      {n:'Módulos / ejes cartesianos', s:'modular y escalable'}
     ]},
    {key:'corte', name:'Herramientas de corte e insertos', brand:'Edición 2026', intro:'Insertos de torneado, fresado, ranurado y carburo sólido.',
     filtros:['Insertos','Torneado','Fresado','Ranurado','Roscado','Carburo sólido'],
     datos:['Designación ISO / geometría','Material a maquinar','Grado','Portaherramienta','Avance y velocidad'],
     fallas:['Filo desgastado','Mal acabado','Vida corta del inserto'],
     aplicaciones:['Torno CNC','Centros de maquinado','Producción metalmecánica'],
     products:[
      {n:'Insertos acero — acabado', s:'JHQ · SPF · STF · JMQ · MSF'},
      {n:'Insertos acero — semiacabado', s:'SPM · TM · MSL · MVL · STM'},
      {n:'Insertos acero — desbaste', s:'SPR · STR'},
      {n:'Acero inoxidable', s:'MAL · SMF · anti-adherencia'},
      {n:'Torneado hierro fundido', s:'rompevirutas general · TK'},
      {n:'Insertos para aluminio', s:'geometría M'},
      {n:'Corte y ranurado', s:'parting & grooving'},
      {n:'Insertos de cermet', s:'acabado fino'},
      {n:'Insertos cerámicos', s:'altas velocidades'},
      {n:'Tronzado y ranurado', s:'insertos dedicados'},
      {n:'Insertos de roscado', s:'métricas y especiales'},
      {n:'Torno tipo suizo', s:'mecanizado de barra'},
      {n:'Carburo sólido', s:'fresas y brocas'},
      {n:'Grados CVD', s:'HK3125 · HK3115'},
      {n:'Grados PVD', s:'HT2015 · HT2030 · HM2035 · HT2065'}
     ]},
    {key:'iqf', name:'Refrigeración industrial / IQF', brand:'ARICO', intro:'Congelación rápida y línea de frío para alimentos y acuacultura.',
     filtros:['Túneles IQF','Evaporadores','Controles','Ventiladores','Sensores de temp.','Componentes'],
     datos:['Tipo de equipo','Capacidad / temperatura','Producto a congelar','Marca / modelo','Aplicación'],
     fallas:['Pérdida de temperatura','Falla de control','Desempeño bajo'],
     aplicaciones:['Alimentos','Congelado IQF','Cadena de frío'],
     products:[
      {n:'Equipos de congelación IQF', s:'Individual Quick Freezing'},
      {n:'Túneles / congeladores de banda', s:'mesh belt · acero inoxidable'},
      {n:'Sistemas mecánicos y eléctricos', s:'para procesamiento de alimentos'},
      {n:'Soluciones para acuacultura', s:'camarón, calamar, pescado'},
      {n:'Equipos personalizables', s:'normativas sanitarias'}
     ]},
    {key:'electrico', name:'Sistemas eléctricos y de control', brand:'', intro:'Componentes de tablero y distribución. Consulta modelos con un asesor.',
     filtros:['Fuentes','Relevadores','Protección','Contactores','Borneras','Botones / pilotos'],
     datos:['Voltaje / corriente','Tipo de componente','Marca / No. de parte','Montaje (riel DIN)','Aplicación'],
     fallas:['Disparo o falla','Componente quemado','Falso contacto'],
     aplicaciones:['Tableros de control','Distribución','Mando de motores'],
     products:[
      {n:'Fuentes de alimentación', s:'24 VDC y especiales'},
      {n:'Relevadores y contactores', s:'mando de motores y cargas'},
      {n:'Protección y breakers', s:'termomagnéticos y guardamotores'},
      {n:'Borneras y riel DIN', s:'distribución de tablero'},
      {n:'Botones, pilotos y señalización', s:'mando e indicación'}
     ]},
    {key:'suministros', name:'Suministros industriales', brand:'', intro:'Componentes para mantenimiento y proyectos. Cuéntanos qué necesitas.',
     filtros:['Mantenimiento','Sujeción','Transmisión','Neumática básica','Eléctrico','Consumibles'],
     datos:['Descripción de la pieza','Marca / No. de parte','Cantidad','Medidas','Aplicación'],
     fallas:['Desgaste por uso','Pieza descontinuada','Difícil de identificar'],
     aplicaciones:['Mantenimiento general','Proyectos','Reposición'],
     products:[
      {n:'Componentes de mantenimiento', s:'reposición y consumo'},
      {n:'Transmisión de potencia', s:'bandas, rodamientos, acoples'},
      {n:'Sujeción y fijación', s:'tornillería y montaje'},
      {n:'Consumibles industriales', s:'para línea y taller'}
     ]}
  ];
  // index by slug per category
  cats.forEach(function(c){
    c.img=imgMap[c.key];
    c.products.forEach(function(p){
      p.slug=slug(p.n);
      p.img=productImgMap[p.slug]||c.img;
    });
  });
  window.KDL = {
    cats: cats,
    img: imgMap,
    productImg: productImgMap,
    slug: slug,
    cat: function(key){ for(var i=0;i<cats.length;i++) if(cats[i].key===key) return cats[i]; return null; },
    find: function(catKey, prodSlug){ var c=this.cat(catKey); if(!c) return null; for(var i=0;i<c.products.length;i++) if(c.products[i].slug===prodSlug) return {cat:c, product:c.products[i]}; return null; }
  };
})();
