[build]
  publish = "."

[[redirects]]
  from = "/Producto.dc.html"
  to = "/productos/:cat/:p/"
  status = 301
  force = true
  query = { cat = ":cat", p = ":p" }

[[redirects]]
  from = "/Productos.dc.html"
  to = "/productos/:cat/"
  status = 301
  force = true
  query = { cat = ":cat" }

